### ISSUE TITLE
Create list of legacy suggestions

### ISSUE THREAD

**Issue by NCSkoglund** [bocks/bocks#33]
Upgrade authentication to use JWT

**Comment by taptapdan** [comment]
An idea. I created a legacy tag that we can apply to Github issues. Then we can just link to the issues with [legacy tags](https://github.com/bocks/bocks/labels/legacy) in the README.

**Comment by taptapdan** [comment]
I'm going to move the "Upgrade authentication to use JWT" suggestion to its own issue and close this one.
