### ISSUE TITLE
Create a +/- font button to change text size of editor/annotations

### ISSUE THREAD

**Issue by NCSkoglund** [bocks/bocks#59]

**Comment by marioyeung** [comment]
We have the following operation to change text size of editor:
editor.setFontSize( <new text size> );

We first need a default font size, say, 18px:
$scope.fontSize = 18;

So when users click on a +/- button, event is triggered. We can define an event-handler like this:
HTML tag: ng-click = 'enlargeText( )'
$scope.enlargeText = function( ) {
     $scope.fontSize += 2; // for example
     editor.setFontSize($scope.fontSize);
}
The same algorithm applies to reduceText.
