### ISSUE TITLE
Determine how to extract snippets from editor for db storage

### ISSUE THREAD

**Issue by NCSkoglund** [bocks/bocks#61]
Also, how to repopulate editor with saved snippets

**Comment by marioyeung** [comment]
To extract snippets from editor, do this:
editor.getValue();

To repopulate editor:
editor.setValue( < saved snippet > );

Yet we can only do with plain text. We may need to create other variables to store all data about highlights.

**Comment by marioyeung** [comment]
Reference: https://ace.c9.io/#nav=howto&api=range
See Common Operations

I also try these commands on browser and they work. I'll write it down on our source code and submit a pull request.
