### ISSUE TITLE
Wire up data model to db

### ISSUE THREAD

**Issue by NCSkoglund** [bocks/bocks#8]
Technical implementation of snippet/highlighting functionality

**Comment by NCSkoglund** [comment]
Should we add a field/array for tags to improve search filter?

**Comment by taptapdan** [comment]
I like the idea. My notes from our conversation yesterday led me to believe our snippets schema would look something like the following. (Disclaimer, I don't have much Mongo experience so this might be too SQL-esque. << edit: maybe tags get stored in the snippets doc?)

# Database Schema

## Snippets

```
* _id
* userName: String (foreign key)
* title: String
* text: String
* isPrivate: Boolean
* createdAt: Date
* modifiedAt: Date
```

## Tags

```
* _id
* snippetsId (foreign key)
* tag: String
```

**Comment by taptapdan** [comment]
Update from morning meeting: @drewkosta will be creating a beginning model/controller for Snippets functionality. This like insert, findByUser, findAll, etc. Thanks!

**Comment by NCSkoglund** [comment]
Should have a remove function as well
