### ISSUE TITLE
Store order of annotations for loading snippet view

### ISSUE THREAD

**Issue by taptapdan** [bocks/bocks#89]

**Comment by marioyeung** [comment]
I am investigating adjustable height of text editor. Just come up with a raw idea which may help.
We may traverse an array from _document.getElementById('annotations').childNodes_ which returns a sorted array of annotations.
<img width="1280" alt="screen shot 2016-06-03 at 7 43 54 pm" src="https://cloud.githubusercontent.com/assets/14968751/15797157/c5dca222-29c3-11e6-9563-f1ed22edc8f5.png">

In the screenshot I created 4 annotations. After that I dragged the last one to the second place, and the order of annotation in the array is 'updated'.
